
services:

  postgres:
    image: postgres:15
    container_name: parking-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - parking-network

  parking-app:
    build: .
    container_name: parking-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    networks:
      - parking-network

  garage-simulator:
    image: cfontes0estapar/garage-sim:1.0.0
    container_name: parking-simulator
    network_mode: host
    depends_on:
      - postgres
      - parking-app

volumes:
  postgres_data:

networks:
  parking-network:
    driver: bridge 